import React from 'react';
import Icon from './Icon.jsx';

function shortDate(value) {
  const date = new Date(value);
  return Number.isFinite(date.valueOf()) ? new Intl.DateTimeFormat('zh-CN', { month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit', hour12: false }).format(date).replaceAll('/', '-') : '等待生成';
}

export default function Sidebar({ topics, page, onNavigate, online, latestBrief, sources = [], status = {}, range, onCollect, busy, loading, onNewTopic, onStartJob, unreadCount = 0, operationsReady }) {
  const nav = (id, name, active = page === id) => <button key={id} type="button" className={`radar-nav-item ${active ? 'active' : ''}`} aria-label={name} aria-current={active ? 'page' : undefined} onClick={() => onNavigate(id)}>{name}</button>;
  const activeRss = sources.filter(source => source.kind === 'rss' && source.enabled && !source.archived).length;
  const researchWeb = sources.filter(source => source.kind === 'web-research' && !source.archived).length;
  const verifiedWeb = sources.filter(source => source.kind === 'web' && source.status === 'ok').length;
  const xSource = sources.find(source => source.id === 'aisa-x');
  const xStatus = xSource?.error || ['failed', 'error'].includes(xSource?.status) ? 'X 最近导入失败' : xSource?.status === 'ok' ? 'X 已导入' : 'X 尚无实采';
  const monitorWindow = range === 'report' ? '见简报说明' : range === '24h' ? '近 24 小时' : range === '7d' ? '近 7 天' : '全部已采集信息';
  return <header className="radar-header"><div className="radar-masthead"><a className="radar-brand" href="#" onClick={event => { event.preventDefault(); onNavigate('report'); }} aria-label="晴初内容机会雷达首页"><strong>晴初</strong><span>内容机会雷达</span></a><div className="radar-metadata"><span><Icon name="report" size={16}/><span>最新报告：<strong>{loading ? '正在读取…' : latestBrief?.generatedAt ? shortDate(latestBrief.generatedAt) : '等待生成'}</strong></span></span><span><Icon name="feed" size={16}/><span>筛选范围：<strong>{monitorWindow}</strong></span></span><button type="button" className="radar-source-status" onClick={() => onNavigate('sources')} title={`已启用 RSS ${activeRss} 个；历史核验网页 ${verifiedWeb} 个；Codex 搜索补充 ${researchWeb} 个来源；${xStatus}`}><span className={`status-dot ${online ? '' : 'offline'}`}/>{loading ? '正在读取来源状态…' : online ? `免费订阅 ${activeRss} · 搜索补充 ${researchWeb}` : '本地服务连接中断'}</button></div><div className="radar-header-icons"><button type="button" className="button primary radar-update-button" disabled={busy || loading || !online || !operationsReady} onClick={onStartJob}>{busy ? <span className="spinner small"/> : <Icon name="play" size={16}/>}更新并生成选题</button><button type="button" className="icon-button" onClick={onCollect} disabled={busy || loading || !online} aria-label="采集免费来源" title="采集一次免费来源">{busy ? <span className="spinner small"/> : <Icon name="refresh" size={20}/>}</button><button type="button" className="icon-button" onClick={() => onNavigate('sources')} aria-label="打开来源状态" title="来源与连接"><Icon name="source" size={19}/></button></div></div><div className="radar-secondary"><nav aria-label="工作台导航">{nav('report', '内容雷达', ['report', 'hot'].includes(page))}{nav('all', '全部信息')}{nav('starred', '我的收藏')}{nav('sources', '来源状态')}{nav('operations', `运行与通知${unreadCount ? ` · ${unreadCount}` : ''}`)}<label className="radar-topic-select"><select aria-label="监控主题" value={page.startsWith('topic:') ? page : ''} onChange={event => event.target.value && onNavigate(event.target.value)}><option value="" disabled>监控主题</option>{topics.map(topic => <option value={`topic:${topic.id}`} key={topic.id}>{topic.name}{!topic.enabled ? ' · 已暂停' : ''}</option>)}</select></label></nav><div className="radar-secondary-actions"><button type="button" className="text-button" onClick={onNewTopic} disabled={loading}><Icon name="plus" size={14}/>新增主题</button><span className="radar-local-status"><span className={`status-dot ${online ? '' : 'offline'}`}/>{online ? '本地运行' : '离线'}</span></div></div></header>;
}
